### ISSUE TITLE
More munging

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#11]
# munge_polyfun_sumstats.py

PolyFun seems to be working fine on my laptop with the example annotations, but when I try to run it on our cluster with the full annotations I'm running into some errors I can't seem to figure out.

Input:
```
ml python/3.7.3 && python3 ./echolocatoR/tools/polyfun/munge_polyfun_sumstats.py --sumstats /sc/orga/projects/pd-omics/data/nallsEtAl2019/combined_meta/nallsEtAl2019_allSamples_allVariants.mod.txt --n 1474097 --out ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/sumstats_munged.parquet --min-info 0 --min-maf 0
```
Output:
```
[INFO]  Reading sumstats file...
./echolocatoR/tools/polyfun/munge_polyfun_sumstats.py:201: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  df_sumstats = pd.read_table(args.sumstats, delim_whitespace=True)

[INFO]  Done in 9.44 seconds
Traceback (most recent call last):
  File "./echolocatoR/tools/polyfun/munge_polyfun_sumstats.py", line 205, in <module>
    df_sumstats = rename_df_columns(df_sumstats, min_info_score=args.min_info, min_maf=args.min_maf)
  File "./echolocatoR/tools/polyfun/munge_polyfun_sumstats.py", line 76, in rename_df_columns
    chr_column:'CHR', info_col:'INFO', beta_col:'BETA', se_col:'SE', pvalue_col:'P', z_col:'Z'}, errors='ignore')
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/pandas/util/_decorators.py", line 197, in wrapper
    return func(*args, **kwargs)
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 4025, in rename
    return super(DataFrame, self).rename(**kwargs)
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/pandas/core/generic.py", line 1072, in rename
    'argument "{0}"'.format(list(kwargs.keys())[0]))
TypeError: rename() got an unexpected keyword argument "errors"
```

It seems do be related to the summ stats renaming but I can't find anything wrong with that part of the code.

**Comment by omerwe** [comment]
It looks to me like the cluster may have an older version of pandas... The "errors" argument  of the rename function was only added in version 0.25.0. The  PolyFun readme and code say that you need pandas version 0.24.0, but I now realize that's a mistake --- I'll update them to require version 0.25.0....  Thanks for helping me catch this!!

**Comment by bschilder** [comment]
Ahh, that'll do it. I think our cluster has multiple versions of pandas, so I'll check that I'm loading the most updated one. Thanks!
