### ISSUE TITLE
missing SNPs

### ISSUE THREAD

**Issue by bschilder** [omerwe/polyfun#15]
So I'm on step 2 of [Polyfun approach 3](https://github.com/omerwe/polyfun/wiki/1.-Computing-prior-causal-probabilities-with-PolyFun) and I'm getting the following error (despite having the `--allow-missing` flag on. I'm using 1KG Phase 1 as a reference (`--bfile-chr `) at the moment. Do you know what might be going on?

```
python ./echolocatoR/tools/polyfun/polyfun.py --compute-ldscores --output-prefix ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS --bfile-chr /sc/orga/projects/pd-omics/data/1000_Genomes/Phase1/1000G.mac5eur. --chr 12 --allow-missing
*********************************************************************
* PolyFun (POLYgenic FUNctionally-informed fine-mapping)
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[WARNING]  no ld-wind argument specified.  PolyFun will use --ld-cm 1.0
Traceback (most recent call last):
  File "./echolocatoR/tools/polyfun/polyfun.py", line 902, in <module>
    polyfun_obj.polyfun_main(args)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 835, in polyfun_main
    self.compute_ld_scores(args)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 697, in compute_ld_scores
    df_ldscores_chr = self.compute_ldscores_plink_chr(args, chr_num, df_bins_chr)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 747, in compute_ldscores_plink_chr
    raise ValueError('Not all SNPs were assigned a bin (meaning some SNPS are not in the annotation files)')
ValueError: Not all SNPs were assigned a bin (meaning some SNPS are not in the annotation files)
```

**Comment by omerwe** [comment]
Hi Brian,

Sorry, I modified the code to allow for mismatch between plink and annotation files. In general, this is not optimal for fine-mapping. You may be omitting the causal SNP, simply because it happened to not have any functional annotations info... However, assuming that this happens mostly for rare SNPs, it's probably not a major issue... 

Can you please try and let me know if it works now?

**Comment by bschilder** [comment]
Hmm, I see your point. I wonder what a better default might be for the SNPs with missing annotations. Like assigning is a resulting prior prob of 0, or 0.5 maybe? though this also seems biased.

Got a little bit further this time after the update!

```
python ./echolocatoR/tools/polyfun/polyfun.py --compute-ldscores --output-prefix ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS --bfile-chr /sc/orga/projects/pd-omics/data/1000_Genomes/Phase1/1000G.mac5eur. --chr 12 --allow-missing
*********************************************************************
* PolyFun (POLYgenic FUNctionally-informed fine-mapping)
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[WARNING]  no ld-wind argument specified.  PolyFun will use --ld-cm 1.0
[WARNING]  Not all SNPs were assigned a bin (meaning some SNPS are not in the annotation files)
[WARNING]  Keeping only 428605/443708 SNPs in chromosome 12 that have annotations
[INFO]  Loading SNP file...
[INFO]  Applying SNPs filter...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 428605/428605 [00:06<00:00, 63814.07it/s]
[INFO]  After filtering, 428605 SNPs remain
Traceback (most recent call last):
  File "./echolocatoR/tools/polyfun/polyfun.py", line 914, in <module>
    polyfun_obj.polyfun_main(args)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 847, in polyfun_main
    self.compute_ld_scores(args)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 697, in compute_ld_scores
    df_ldscores_chr = self.compute_ldscores_plink_chr(args, chr_num, df_bins_chr)
  File "./echolocatoR/tools/polyfun/polyfun.py", line 804, in compute_ldscores_plink_chr
    coords = np.array(df_bim['CM'])[geno_array.kept_snps]
IndexError: index 428605 is out of bounds for axis 0 with size 428605
```

**Comment by bschilder** [comment]
Trying to backtrack a bit and thinking about why there's so many missing SNPs in the annotations to begin with. I wonder if it has to do with the way the summstats are being merged in `polyfun.py`, which I think is merging only by SNP/RSID, A1, and A2. Maybe trying to merge by CHR & BP first (if these cols are available) and if not, then trying to merge by SNP. The idea being that merging by CHR & BP might be a little robust to how SNPs are labeled?


```
        if args.sumstats.endswith('.parquet'): df_sumstats = pd.read_parquet(args.sumstats)            
        else: df_sumstats = pd.read_table(args.sumstats, delim_whitespace=True)            
        df_sumstats.drop(columns=['CHR', 'BP'], errors='ignore', inplace=True)
        for col in ['SNP', 'A1', 'A2']:
            if col not in df_sumstats.columns:
                raise ValueError('sumstats file has a missing column: %s'%(col))        
        df_snpvar = df_snpvar.merge(df_sumstats, on=['SNP', 'A1', 'A2'])
```

**Comment by omerwe** [comment]
Oops, please try my bugfix.
I don't think it's a good idea to give a "special" treatment to SNPs without annotations. The question is indeed what are these SNPs that don't have annotations. One thing you could do is run the script munge_polyfun_sumstats.py with --allow-missing. It should print out a list of all the SNPs with on annotations info. Then you could try figuring out what's special about these SNPs. my guess is they're rare, but it's worth checking.

I'm not sure CHR,BP is a better merge field than SNP, because SNP is supposed to be based on rsid, which should have a unique mapping to CHR,BP...

**Comment by bschilder** [comment]
Hi Omer, 

Just tried the latest bug fix to try and keep more of the SNPs:

## Munge
This step seems to be going much better, it isn't throwing out half the SNPs like before.
```
python ./echolocatoR/tools/polyfun/munge_polyfun_sumstats.py --sumstats /sc/orga/projects/pd-omics/data/nallsEtAl2019/combined_meta/nallsEtAl2019_allSamples_allVariants.mod.txt --n 1474097 --out /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet --min-info 0 --min-maf 0.001
[INFO]  Reading sumstats file...
[INFO]  Done in 7.41 seconds
[INFO]  7798414 SNPs are in the sumstats file
[INFO]  Removing 34202 HLA SNPs
[INFO]  7764212 SNPs with sumstats remained after all filtering stages
[INFO]  Saving munged sumstats of 7764212 SNPs to /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet
[INFO]  Done
```

## Calculate LD Scores
But a similar issue as before now seems to be happening at the step where the sumstats get merged with at the ` After merging with reference panel LD, 3483859 SNPs remain` step (reducing the # of SNPS from ~7.7M => ~3.5M). 
```
python ./echolocatoR/tools/polyfun/polyfun.py --compute-h2-L2  --output-prefix ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS --sumstats /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet --ref-ld-chr /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/baselineLF2.2.UKB. --w-ld-chr /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/weights.UKB. --allow-missing
*********************************************************************
* PolyFun (POLYgenic FUNctionally-informed fine-mapping)
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[INFO]  Reading summary statistics from /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet ...
[INFO]  Read summary statistics for 7764212 SNPs.
[INFO]  Dropped 5750 SNPs with duplicated rs numbers.
[INFO]  Reading reference panel LD Score from /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/baselineLF2.2.UKB.[1-22] ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [01:23<00:00,  3.78s/it]
[INFO]  Read reference panel LD Scores for 19386297 SNPs.
[INFO]  Reading regression weight LD Score from /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/weights.UKB.[1-22] ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:17<00:00,  1.26it/s]
[INFO]  Read regression weight LD Scores for 18275613 SNPs.
[INFO]  After merging with reference panel LD, 3483859 SNPs remain.
[INFO]  After merging with regression SNP LD, 3476469 SNPs remain.
[INFO]  iterating over chromosomes to compute XTX, XTy...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:12<00:00,  1.70it/s]
[INFO]  Evaluating Ridge lambdas...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:08<00:00, 12.39it/s]
[INFO]  Selected ridge lambda: 7.5683e-01 (79/100)  score: 6.3286e-02  score lstsq: 6.1667e-02
[INFO]  Estimating annotation coefficients for each chromosomes set                                                                                                            
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.73s/it]
[INFO]  Computing per-SNP h^2 for each chromosome...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [01:08<00:00,  3.10s/it]
[INFO]  Saving constrained SNP variances to disk
[WARNING]  not all SNPs in the sumstats file are also in the annotations file
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:43<00:00,  1.97s/it]
[INFO]  Saving SNP variances to disk
[WARNING]  not all SNPs in the sumstats file are also in the annotations file
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:47<00:00,  2.14s/it]
[INFO]  Clustering SNPs into bins using the R Ckmeans.1d.dp package
[INFO]  Determining the optimal number of bins (if this is slow, consider using --num-bins 20 (or some other number))
[INFO]  Ckmedian.1d.dp partitioned SNPs into 30 bins
[INFO]  Saving SNP-bins to disk
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:17<00:00,  1.29it/s]

```

**Comment by omerwe** [comment]
Hi Brian,

Good catch! This was because of allelic flips between the sumstats and the
annotation files (in code buried deep in the original LDSC code). I just
fixed it as well --- please retry. Sorry for all these hassles!

**Comment by bschilder** [comment]
No worries, thanks for all your help.

Tried the update, and according to the command line messages everything seemed to be going great: 7697657/7715760 SNPs (99.8%) were retained. But when I went to actually import the `*.snp_constrained.gz` files with h<sup>2</sup> (SNPVAR), I noticed there were only ~3.5M SNPs actually in the files again.

## [2] Run PolyFun with L2-regularized S-LDSC. (*all seems good here*)
```
python ./echolocatoR/tools/polyfun/polyfun.py --compute-h2-L2  --output-prefix ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS --sumstats /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet --ref-ld-chr /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/baselineLF2.2.UKB. --w-ld-chr /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/weights.UKB. --allow-missing
*********************************************************************
* PolyFun (POLYgenic FUNctionally-informed fine-mapping)
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[INFO]  Reading summary statistics from /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet ...
[INFO]  Read summary statistics for 7764212 SNPs.
[INFO]  Dropped 13865 duplicated SNPs.
[INFO]  Reading reference panel LD Score from /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/baselineLF2.2.UKB.[1-22] ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [01:51<00:00,  5.08s/it]
[INFO]  Read reference panel LD Scores for 19386297 SNPs.
[INFO]  Reading regression weight LD Score from /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/weights.UKB.[1-22] ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:46<00:00,  2.11s/it]
[INFO]  Read regression weight LD Scores for 18275613 SNPs.
[INFO]  After merging with reference panel LD, 7715760 SNPs remain.
[INFO]  After merging with regression SNP LD, 7697657 SNPs remain.
[INFO]  iterating over chromosomes to compute XTX, XTy...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:28<00:00,  1.31s/it]
[INFO]  Evaluating Ridge lambdas...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:19<00:00,  5.12it/s]
[INFO]  Selected ridge lambda: 7.5773e-01 (79/100)  score: 6.6535e-02  score lstsq: 6.5135e-02
[INFO]  Estimating annotation coefficients for each chromosomes set                                                                                                            
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.95s/it]
[INFO]  Computing per-SNP h^2 for each chromosome...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [01:02<00:00,  2.86s/it]
[INFO]  Saving constrained SNP variances to disk
[WARNING]  not all SNPs in the sumstats file are also in the annotations file
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:44<00:00,  2.01s/it]
[INFO]  Saving SNP variances to disk
[WARNING]  not all SNPs in the sumstats file are also in the annotations file
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:47<00:00,  2.17s/it]
[INFO]  Clustering SNPs into bins using the R Ckmeans.1d.dp package
[INFO]  Determining the optimal number of bins (if this is slow, consider using --num-bins 20 (or some other number))
[INFO]  Ckmedian.1d.dp partitioned SNPs into 25 bins
[INFO]  Saving SNP-bins to disk
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:16<00:00,  1.34it/s]

```

##  [3] Compute LD-scores for each SNP bin

```
Fine_Mapping]$ python ./echolocatoR/tools/polyfun/polyfun.py --compute-ldscores --output-prefix ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS --bfile-chr /sc/orga/projects/pd-omics/data/1000_Genomes/Phase1/1000G.mac5eur.  --allow-missing
*********************************************************************
* PolyFun (POLYgenic FUNctionally-informed fine-mapping)
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[WARNING]  no ld-wind argument specified.  PolyFun will use --ld-cm 1.0
[WARNING]  Not all SNPs were assigned a bin (meaning some SNPS are not in the annotation files)                                                                                
[WARNING]  Keeping only 693127/711593 SNPs in chromosome 1 that have annotations                                                                                               
[INFO]  Loading SNP file...                                                                                                                                                    
[INFO]  Applying SNPs filter...                                                                                                                                                
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 693127/693127 [00:10<00:00, 68896.98it/s]
[INFO]  After filtering, 693127 SNPs remain                                                                                                                                    
[INFO]  Computing LD scores for chromosome 1                                                                                                                                   
[INFO]  Applying initial ldscores loop                                                                                                                                         
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 754.39it/s]
[INFO]  Applying main ldscores loop...                                                                                                                                         
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13834/13834 [01:42<00:00, 135.54it/s]

```

## [4] Re-estimate per-SNP heritabilities via S-LDSC
This step also seems to be retained most of the SNPs (7574933/7574933), yet the files being written (`*.snp_constrained.gz`) only contain half as many. So close!
```
python ./echolocatoR/tools/polyfun/polyfun.py --compute-h2-bins --output-prefix ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS --sumstats /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet --w-ld-chr /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/weights.UKB. --allow-missing
*********************************************************************
* PolyFun (POLYgenic FUNctionally-informed fine-mapping)
* Version 1.0.0
* (C) 2019 Omer Weissbrod
*********************************************************************

[INFO]  Reading summary statistics from /sc/orga/projects/pd-omics/tools/polyfun/Nalls23andMe_2019.sumstats_munged.parquet ...
[INFO]  Read summary statistics for 7764212 SNPs.
[INFO]  Dropped 13865 duplicated SNPs.
[INFO]  Reading reference panel LD Score from ./Data/GWAS/Nalls23andMe_2019/_genome_wide/PolyFun/output/PD_GWAS.[1-22] ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:24<00:00,  1.12s/it]
[INFO]  Read reference panel LD Scores for 9010021 SNPs.
[INFO]  Reading regression weight LD Score from /sc/orga/projects/pd-omics/tools/polyfun/annotations/baselineLF2.2.UKB/weights.UKB.[1-22] ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:45<00:00,  2.05s/it]
[INFO]  Read regression weight LD Scores for 18275613 SNPs.
[INFO]  After merging with reference panel LD, 7574933 SNPs remain.
[INFO]  After merging with regression SNP LD, 7554107 SNPs remain.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [02:09<00:00,  5.91s/it]
[INFO]  Computing per-SNP h^2 for each chromosome...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:12<00:00,  1.82it/s]
[INFO]  Saving constrained SNP variances to disk
[WARNING]  not all SNPs in the sumstats file are also in the annotations file
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:40<00:00,  1.84s/it]
```

**Comment by omerwe** [comment]
Hi Brian,

Sorry sorry sorry! This is tricky stuff! Can you please try again with the
revised code? Fingers crossed!

**Comment by bschilder** [comment]
Success! Everything seems to be working end-to-end now (~7M SNPs are now in the results files). Thanks so much!
