### ISSUE TITLE
PolyPred not recognizing my bed file

### ISSUE THREAD

**Issue by bcoombes** [omerwe/polyfun#165]
I am running this code

python polypred.py \
--combine-betas \
--betas $projdir/polyfun_susie_hrc_allelesaligned.txt, $projdir/prsweights_allelesaligned.txt \
--pheno $projdir/gainpheno.txt \
--output-prefix polypredout \
--extract $projdir/extractsnps.txt \
--plink-exe plink \
$beddir/GENO.bed

where I have confirmed that the pheno file has the correct headers FID IID PHENO and I have made sure my betas are all corresponding to the same A1 allele. However, I am getting this error: 

polypred.py: error: unrecognized arguments: [insert file path]/GENO.bed

I have also tried running this using the bed files provided in the example and it tells me it doesn't recognize that list of 1000G.subset bed files. If I remove the last line (providing no bed file), I get this error: 

Traceback (most recent call last):
  File "/research/bsi/tools/biotools/polyfun/1.0.0/polyfun/polypred.py", line 430, in <module>
    estimate_mixing_weights(args)
  File "/research/bsi/tools/biotools/polyfun/1.0.0/polyfun/polypred.py", line 283, in estimate_mixing_weights
    df_prs_sum = computs_prs_all_files(args, betas_file, disable_jackknife=True, keep_file=args.pheno)
  File "/research/bsi/tools/biotools/polyfun/1.0.0/polyfun/polypred.py", line 213, in computs_prs_all_files
    raise ValueError('File suffix must be either .bed or .pgen')
ValueError: File suffix must be either .bed or .pgen

So the script is looking for a bed file but doesn't recognize bed files. Any help you can provide is appreciated. Thanks!

**Comment by bcoombes** [comment]
It was the space between the beta weights files.
