### ISSUE TITLE
ModuleNotFoundError: No module named 'bitarray' error

### ISSUE THREAD

**Issue by cmlakhan** [omerwe/polyfun#62]
I don't know if I'm the only one having this issue but I recently tried to run ldscore regression using the PolyFun package and I got this error

```
Traceback (most recent call last):
  File "ldsc.py", line 12, in <module>
    import ldsc_polyfun.ldscore as ld
  File "/gpfs/commons/home/clakhani/gitProjects/polyfun/ldsc_polyfun/ldscore.py", line 3, in <module>
    import bitarray as ba
ModuleNotFoundError: No module named 'bitarray'

```

It has worked for me in the past was there a recent change that may have caused this problem?

This is the command that I tried to execute

```

source /gpfs/commons/groups/knowles_lab/software/anaconda3/bin/activate
conda activate polyfun




cd
cd /gpfs/commons/home/clakhani/gitProjects/polyfun

bl='/gpfs/commons/groups/knowles_lab/data/ldsc/polyfun/baselineLF2.2.UKB/baselineLF2.2.UKB.'
other='/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations/combined_AD_annotations_polyfun/combined_AD_annotations_polyfun_'
brain_H3K4me3='/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations/brain_H3K4me3/merged_annotations_ukb/brain_H3K4me3_seq_chr'
brain_H3K27ac='/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations/brain_H3K27ac/merged_annotations_ukb/brain_H3K27ac_seq_chr'
weight='/gpfs/commons/groups/knowles_lab/data/ldsc/polyfun/baselineLF2.2.UKB/weights.UKB.'
path_sumstats='/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/bellenguez_2021/Bellenguez_2021_stage1.parquet'
path_out='/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/joint_analysis/AD_Bellenguez_joint_'


python ldsc.py	--h2 $path_sumstats \
--ref-ld-chr $bl,$other,$brain_H3K4me3,$brain_H3K27ac \
--w-ld-chr $weight \
--overlap-annot \
--out $path_out \
--overlap-annot \
--not-M-5-50 \
--print-coefficients \
--print-delete-vals

```

I pulled the most recent code from GitHub and also recreated the polyfun environment  using your yml file, so I don't think it's an issue with my Conda environment

**Comment by omerwe** [comment]
Hi,

bitarray should be installed (it's in the yml file containing the conda environment), so it's unclear why it can't be found.
You can try manually installing it, using either one of the following two commands (after running "conda activate polyfun"):

- pip install bitarray
-  conda install -c anaconda bitarray

Can you please let me know if this resolved the problem?

**Comment by omerwe** [comment]
Great! I'm closing the issue...

**Comment by cmlakhan** [comment]
Thank you!
